# Generated by Django 5.2.8 on 2025-11-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cretonetApp', '0003_project_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='téléphone',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
