# Generated by Django 5.2.8 on 2025-12-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cretonetApp', '0005_message_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='budget_min',
        ),
    ]
