# Generated by Django 5.2.8 on 2025-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cretonetApp', '0006_remove_offer_budget_max_remove_offer_budget_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(default='En ligne', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='required_profile',
            field=models.CharField(default='Designer', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('completed', 'Terminé')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='work_mode',
            field=models.CharField(choices=[('online', 'En ligne'), ('onsite', 'Présentiel'), ('hybrid', 'Hybride')], default='online', max_length=20),
        ),
    ]
