# Generated by Django 5.2.8 on 2026-02-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cretonetApp', '0009_message_lu_alter_message_destinataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='cretonetApp.offer'),
        ),
    ]
