# Generated by Django 5.2.8 on 2026-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cretonetApp', '0011_project_status_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('available', 'Disponible'), ('completed', 'Terminé')], default='draft', max_length=20),
        ),
    ]
