# Generated by Django 5.2.8 on 2026-03-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cretonetApp', '0012_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('available', 'Disponible'), ('completed', 'Terminé'), ('rejected', 'Refusé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation IA'), ('published', 'Publié'), ('rejected', 'Refusé')], default='draft', max_length=20),
        ),
    ]
